services:
  - type: web
    name: pashu-setu-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SUPABASE_URL
        value: https://liqvncjksywdybfbbxmk.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false