-- Add missing columns to animals table
ALTER TABLE animals ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE animals ADD COLUMN IF NOT EXISTS tag_number VARCHAR(100);
ALTER TABLE animals ADD COLUMN IF NOT EXISTS vaccination_status VARCHAR(100);
ALTER TABLE animals ADD COLUMN IF NOT EXISTS microchip_id VARCHAR(100);
ALTER TABLE animals ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'healthy';
ALTER TABLE animals ADD COLUMN IF NOT EXISTS weight DECIMAL(10,2);